import Footer from '@/components/Footer'
import Header from '@/components/Header'
// import Navbar from '@/components/navbar'
import '@/styles/globals.css'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return <> 
  <Head>
  <title>AR Travels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/@material-tailwind/html@latest/scripts/collapse.js"></script> {/*cdn link for accordin*/}

  </Head>
  <Header/>
  <Component {...pageProps} />
  <Footer/>
  </>
}
