import Footer from '@/components/Footer'
import Header from '@/components/Header'
// import Navbar from '@/components/navbar'
import '@/styles/globals.css'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return <>
    <Head>
      <title>visituttrakhand.in</title>
      <script id="gs-sdk" src='//www.buildquickbots.com/botwidget/v3/demo/static/js/sdk.js?v=3' key="2bxx79xx-0dxb-4xx4-ac71-x4a42xxxxxxx"></script>

      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <script src="https://unpkg.com/@material-tailwind/html@latest/scripts/collapse.js"></script> {/*cdn link for accordin*/}
    </Head>
    <Component   {...pageProps} />
    <Footer />
  </>
}
