import Footer from '@/components/Footer'
import Header2 from '@/components/Header2'
// import Navbar from '@/components/navbar'
import '@/styles/globals.css'
import Head from 'next/head'
import Script from 'next/script'
import React,{useEffect} from 'react'
import AOS from 'aos';
import "aos/dist/aos.css";

export default function App({ Component, pageProps }) {
 
  useEffect(() => {
    AOS.init({
      duration:1000,
    });
  },)
 return <>
    <Head>
      <title>visituttrakhand.in</title>
      <Script id="gs-sdk" src='//www.buildquickbots.com/botwidget/v3/demo/static/js/sdk.js?v=3' key="2bxx79xx-0dxb-4xx4-ac71-x4a42xxxxxxx"/>

      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <Script src="https://unpkg.com/@material-tailwind/html@latest/scripts/collapse.js"/>
      {/* <script src="https://unpkg.com/@material-tailwind/html@latest/scripts/collapse.js"></script> cdn link for accordin */}
    </Head>
    <Header2/>
    <Component   {...pageProps} />
    <Footer />
  </>
}
