import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import Navbar from '@/components/navbar'
import data from "../data/plans.json"
import { useEffect } from 'react'
import OffersCard from '@/components/HomeScreenComponents/OffersCard'
const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  useEffect(() => {
    console.log(data);
  }, [])
  return (
    <>
      <Head>
        <title>AR-Travels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='w-full'>
          <img className='w-full' src="https://firebasestorage.googleapis.com/v0/b/artravells.appspot.com/o/4-dham-only.png?alt=media&token=c1f3fbe2-8195-4e81-b3f2-3ed8e9373145" alt="" />
        </div>
      <main className='xl:container'>
        <section className='mx-2 md:mx-10 my-10 rounded-md px-4 py-5 bg-slate-100'>
          <h1 className='font-bold text-2xl text-justify'>We At AR Travels</h1>
          <p className='text-justify mt-2'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium tempora sit qui vero, laudantium adipisci at laboriosam molestias distinctio asperiores temporibus officiis quas. Nulla esse aliquid, consequatur enim repellat excepturi?
            Perspiciatis in quam cumque velit praesentium sit laudantium iure fuga reiciendis necessitatibus, expedita eos debitis, fugit, aperiam odio asperiores voluptate error tenetur vero et repellat ipsam! Illum architecto asperiores perspiciatis?
            Rem temporibus accusamus molestias odio aliquam commodi assumenda fugiat perspiciatis saepe. Modi nisi autem quasi delectus inventore quos. Facere fugiat numquam, ullam inventore tempore iste maxime id officiis quibusdam illo.
            Cupiditate culpa vitae minus fugiat tenetur omnis in vero eos! Provident, accusamus vitae! Illum itaque iste pariatur, placeat possimus ullam nesciunt? Voluptates, officiis dolor. Rerum a cumque tempora architecto eaque?
            Recusandae quis sed officiis asperiores? Et corrupti tenetur autem exercitationem magnam placeat, recusandae velit dolorem debitis iusto consectetur cumque fuga ut eveniet totam libero laboriosam doloremque repudiandae odio praesentium dolor.</p>
        </section>

        {/* group plans */}
        <div className='mt-10'>
          <h1 className='text-3xl font-semibold my-4 tracking-wide text-center'>GROUP PLANS</h1>
          <div className='grid grid-cols-1 md:grid-cols-2 gap-6 mx-2 md:mx-0'>
          {
            data.groupPlans.map((gplan) => {
              return <OffersCard plan={gplan}/>
            })
          }
        </div>
        </div>
        <div className='mt-10'>
          <h1 className='text-3xl font-semibold my-4 tracking-wide text-center'>PLANS</h1>
          <div className='grid grid-cols-1 md:grid-cols-3 gap-6'>
          {data.plans.map((plan) => {
            return <OffersCard plan={plan}/>
          })}
        </div>
        </div>

      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  return {
    props: { data }, // will be passed to the page component as props
  }
}